---
title: "Intervention_Social_Ind"
author: ""
date: "2025-03-04"
output: html_document
---

```{r 0.1.INSTALL_LIBRARIES}

###INSTALL LIBRARIES IF NEEDED
# sudo apt install libharfbuzz-dev 
# sudo apt install libfribidi-dev
install.packages("Matrix", dependencies = TRUE)

packages <- c("foreign", "ggplot2", "readr", "tidyverse", "lsr", "effsize", "effectsize", 
              "PupillometryR", "Rmisc", "see", "ggpubr", "gghalves", "stargazer", 
              "jmvReadWrite", "AlphaPart", "car", "dplyr", "ggalluvial", "nnet", 
              "lme4", "BayesFactor", "brms")

# Install missing packages
install_if_missing <- function(pkg) {
  print(pkg)
  if (!requireNamespace(pkg, quietly = TRUE)) {
    install.packages(pkg, dependencies = TRUE)
  }
  library(pkg, character.only = TRUE)
}

# Install and load packages
lapply(packages, install_if_missing)

# Detach plyr if loaded to avoid conflicts with dplyr
if ("package:plyr" %in% search()) {
  detach("package:plyr", unload = TRUE)
}

```

```{r 0.2.LOAD_LIBRARIES}

#LOAD LIBRARIES 

library(foreign)
library(ggplot2)
library(readr)
library(tidyverse)
library(lsr)
library(effsize)
library(effectsize)
library(PupillometryR)
library(Rmisc)
library(see)
library(ggpubr)
library(gghalves)
library(stargazer)
library(jmvReadWrite)
library(AlphaPart)
library(car)
library(dplyr)
detach(package:plyr)
library(ggalluvial)
library(nnet)
library(lme4)
library(BayesFactor)
library(brms)
```

```{r 0.2.LOAD_DATA}

#
# setwd("/Users/nadirdiazsimon/Library/CloudStorage/OneDrive-TheUniversityofWesternOntario/ZZ.PREVIOUS_WORK/COGNUM_UY/Intervention2021")

interv.exp <- read.csv("PeerMathIntervention_v2.csv")

```

```{r METHODS_PARTICIPANTS_DESCRIPTIVE_AGE}
#whole sample
mean(interv.exp$Age, na.rm=T)/12
sd(interv.exp$Age, na.rm=T)/12
min(interv.exp$Age, na.rm=T)/12
max(interv.exp$Age, na.rm=T)/12

interv.exp %>%
  dplyr::group_by(Gender) %>%
  dplyr::summarize(
    n = n(),  # Count total participants in each group
    n_fem = n()/112*100,  
  )

interv.exp %>%
  dplyr::group_by(Grade) %>%  # Group by Grade only
  dplyr::summarize(
    n_total = n(),  # Total number of participants in each Grade
    n_females = sum(Gender == "Female", na.rm = TRUE),  # Count of females
    n_males = sum(Gender == "Male", na.rm = TRUE),    # Count of males
    perc_females = (n_females / n_total) * 100,  # Percentage of females
    perc_males = (n_males / n_total) * 100       # Percentage of males
  )

interv.exp %>%
  dplyr::group_by(Grade) %>%
  dplyr::summarize(
    n = n(),  # Count total participants in each group
    n_fem = sum(Gender == "Female", na.rm = TRUE)/n()*100,  
    M = mean(Age, na.rm = TRUE)/12,  
    SD = sd(Age, na.rm = TRUE)/12,
    min = min(Age, na.rm = TRUE)/12,
    max = max(Age, na.rm = TRUE)/12
  )

interv.exp %>%
  dplyr::group_by(Training) %>%
  dplyr::summarize(
    n = n(),  # Count total participants in each group
    n_fem = sum(Gender == "Female", na.rm = TRUE)/n()*100, 
    M = mean(Age, na.rm = TRUE)/12,  
    SD = sd(Age, na.rm = TRUE)/12,
    min = min(Age, na.rm = TRUE)/12,
    max = max(Age, na.rm = TRUE)/12
  )

leveneTest(Age ~ Training, data = interv.exp)
t.test(Age ~ Training, data = interv.exp, paired=F, var.equal=T, alternative="two.sided")
cohen.d(Age ~ Training, data = interv.exp)

interv.exp %>%
  dplyr::group_by(Grade, Training) %>%  # Group by Grade only
  dplyr::summarize(
    n_total = n())
```

```{r DESCRIPTIVE_DIRECT_SCORE}
interv.exp %>%
  dplyr::group_by(Grade) %>%
  dplyr::summarize(n = length(a_DS_PUMA_PRE),
                   M = mean(a_DS_PUMA_PRE),
                   SD = sd(a_DS_PUMA_PRE))
```

```{r TERCILES}
interv.exp <- interv.exp %>%
  group_by(Grade) %>%
  mutate(
    # Standardize pre- and post-test scores using pre-test stats
    a_ZS_PUMA_PRE = ((a_DS_PUMA_PRE - mean(a_DS_PUMA_PRE, na.rm = TRUE)) / (sd(a_DS_PUMA_PRE, na.rm = TRUE))),
    b_ZS_PUMA_POST =((b_DS_PUMA_POST - mean(a_DS_PUMA_PRE, na.rm = TRUE)) / sd(a_DS_PUMA_PRE, na.rm = TRUE))) %>%
  ungroup() # Ungroup the data for further analysis

interv.exp <- interv.exp %>%
  mutate(
    # Divide pre- and post-test scores into tertiles
    a_TERC_PUMA_PRE = ntile(a_ZS_PUMA_PRE, 3))

pre_cutoffs <- quantile(interv.exp$a_ZS_PUMA_PRE, probs = c(1/3, 2/3), na.rm = TRUE)
post_cutoffs <- quantile(interv.exp$b_ZS_PUMA_POST, probs = c(1/3, 2/3), na.rm = TRUE)


print(pre_cutoffs)
print(post_cutoffs)

interv.exp <- interv.exp %>%
  mutate(a_TERC_PUMA_PRE = case_when(a_TERC_PUMA_PRE == "1"  ~ "Beginner",
                                     a_TERC_PUMA_PRE== "2"  ~ "Intermediate",
                                     a_TERC_PUMA_PRE == "3"  ~ "Proficient"))
interv.exp <- interv.exp %>%
  mutate(b_TERC_PUMA_POST = case_when(
    b_ZS_PUMA_POST < -0.446 ~ "Beginner",
    b_ZS_PUMA_POST >= -0.446 & b_ZS_PUMA_POST <= 0.343 ~ "Intermediate",
    b_ZS_PUMA_POST > 0.343 ~ "Proficient"
  ))
```

```{r GAIN_AND_STD_GAIN}
interv.exp$c_ZS_PUMA_DELTA <- interv.exp$b_ZS_PUMA_POST - interv.exp$a_ZS_PUMA_PRE

interv.exp <- interv.exp %>%
  group_by(Training) %>%  # Group by Training
  mutate(
    d_ZS_PUMA_StdGain = (b_ZS_PUMA_POST - a_ZS_PUMA_PRE) / (sd(a_ZS_PUMA_PRE, na.rm = TRUE))  # Compute Standardized Gain
  ) %>%
  ungroup()  # Ungroup after computation

write_csv(interv.exp, file = "PeerMathIntervention_v2.csv")
```

```{r PRE_VS_POST}

interv.exp.long <- interv.exp %>%
  pivot_longer(c( "a_ZS_PUMA_PRE",
                  "b_ZS_PUMA_POST",
  ), names_to = "Time")

interv.exp.long$Time <- as.factor(interv.exp.long$Time)

interv.exp.long <- interv.exp.long %>%
  dplyr::mutate(Training = dplyr::recode(Training, 
                                         "Peer Interaction" = "Social", 
                                         "Individual" = "Individual"))

interv.exp.long %>%
  dplyr::group_by(Time) %>%
  dplyr::summarize(n=length(value),
                   M=round(mean(value), digits=2),
                   SD=round(sd(value), digits=2))

```

```{r T-TEST_PRE_VS_POST}

leveneTest(value ~ Time, data = interv.exp.long)
t.test(value ~ Time, data = interv.exp.long, paired=T, equal.var=T, alternative="two.sided")
cohen.d(interv.exp.long$value ~ interv.exp.long$Time)
```

```{r CONTROL_VS_EXPERIMENTAL_PRETEST}

interv.exp.long%>%
  dplyr::group_by(Time, Training) %>%
  dplyr::summarize(n=length(value),
                   M=mean(value),
                   SD=sd(value))

```

```{r T-TEST_CONTROL_VS_EXPERIMENTAL_PRETEST}
leveneTest(a_ZS_PUMA_PRE ~ Training, data = interv.exp)
t.test(a_ZS_PUMA_PRE ~ Training, data = interv.exp, paired=F, var.equal=T)
cohen.d(a_ZS_PUMA_PRE ~ Training, data = interv.exp)

```

```{r TEMPORAL_STABILITY_DIVIDED}
interv.exp %>%
  dplyr::group_by(Training) %>%
  dplyr::summarize(cor_result = list(cor.test(a_ZS_PUMA_PRE, b_ZS_PUMA_POST)),
                   .groups = "drop") %>%
  dplyr::mutate(df = purrr::map_dbl(cor_result, ~ .x$parameter),
                r = purrr::map_dbl(cor_result, ~ .x$estimate),
                p_value = purrr::map_dbl(cor_result, ~ .x$p.value)) %>%
  dplyr::select(Training, df,r, p_value)
```

```{r ANCOVA_WHOLE_SAMPLE}
ancova_model_aov <- aov(b_ZS_PUMA_POST ~ Training + a_ZS_PUMA_PRE, data = interv.exp)
summary(ancova_model_aov)
Anova(ancova_model_aov, type = "III")
eta_squared(ancova_model_aov)
```

```{r STD_GAIN_CONTROL_VS_EXPERIMENTAL}
interv.exp%>%
  dplyr::group_by(Training) %>%
  dplyr::summarize(n=length(d_ZS_PUMA_StdGain),
                   M=mean(d_ZS_PUMA_StdGain),
                   SD=sd(d_ZS_PUMA_StdGain))

leveneTest(d_ZS_PUMA_StdGain ~ Training, data = interv.exp)
t.test(d_ZS_PUMA_StdGain ~ Training, data = interv.exp, paired=F, var.equal=T)
cohen.d(d_ZS_PUMA_StdGain ~ Training, data = interv.exp)
```

```{r}
interv.exp.long %>%
  dplyr::filter(Time == "b_ZS_PUMA_POST") %>%
  dplyr::group_by(Training) %>%
  dplyr::summarize(M = mean(value))

```

```{r IMPROVEMNET_SCORE}
interv.exp <- interv.exp %>%
  mutate(Improved_score = b_ZS_PUMA_POST > a_ZS_PUMA_PRE)

interv.exp %>%
  dplyr::group_by(Training) %>%
  dplyr::summarise(
    Improved_N = sum(Improved_score, na.rm = TRUE),
    Total_N = n(),  # Explicitly calling dplyr::n() to avoid issues
    Improvement_Percentage = (Improved_N / Total_N) * 100,
    .groups = "drop"  # Avoids unnecessary grouping
  )
```

```{r PLOT_BETWEEN_AND_WITHIN_PRE_VS_POST_CONTROL_AND_EXPERIMENTAL_ALL}
ggplot(interv.exp.long, aes(x=Time, y=value, fill=Training))+
  scale_fill_manual(values=c("#4cd038","#800080"))+
  scale_color_manual(values=c("#4cd038","#800080"))+
  scale_shape_manual(values = c(16, 15)) +
  scale_linetype_manual(values = c("dashed", "solid")) +
  geom_violinhalf(position=position_nudge(), alpha = .5, colour = NA, flip=c(1,2))+
  stat_summary(aes(x=Time, y=value, color=Training, shape=Training, group=Training), 
             fun=mean, geom="point", size=3)+
  stat_summary(aes(color=Training), fun.data = mean_se, geom = "errorbar", fun=mean,position=position_nudge(), width=0.05, size=1.5)+
  stat_summary(aes(group=Training, color=Training, linetype = Training), geom="line", size=1.5)+
  scale_x_discrete(labels= c("Pre-test", "Post-test"))+
  ylab("Z-score PUMA")+
  xlab("Time")+
  theme_classic()+
  theme(legend.position="top",
        text=element_text( size=35, color = "black"), 
        axis.text=element_text(colour = "black", size= 25, face="bold"), 
        axis.line = element_line(colour = 'black', size = 1),
        axis.ticks.y = element_line(size = 1),
        axis.ticks.x = element_blank(),
        axis.line.x = element_line(size = 1), 
        strip.background = element_blank())

```

```{r PLOT_BETWEEN_AND_WITHIN_PRE_VS_POST_CONTROL_AND_EXPERIMENTAL_TERCILES}
ggplot(interv.exp.long, aes(x=Time, y=value, fill=Training))+
  facet_grid(. ~ a_TERC_PUMA_PRE)+
  scale_fill_manual(values=c("#4cd038","#800080"))+
  scale_color_manual(values=c("#4cd038","#800080"))+
  scale_shape_manual(values = c(16, 15)) +
  scale_linetype_manual(values = c("dashed", "solid")) +
  geom_violinhalf(position=position_nudge(), alpha = .5, colour = NA, flip=c(1,2))+
  stat_summary(aes(color=Training, shape=Training), fun=mean,position=position_nudge(),geom="point", size=3)+
  stat_summary(aes(color=Training), fun.data = mean_se, geom = "errorbar", fun=mean,position=position_nudge(), width=0.05, size=1.5)+
  stat_summary(aes(group=Training, color=Training, linetype = Training), geom="line", size=1.5)+
  scale_x_discrete(labels= c("Pre-test", "Post-test"))+
  #scale_y_continuous(limits=c(-3, 4), breaks=c(-3,-2, -1, 0, 1, 2, 3,4))+
  geom_hline(yintercept=-0.446, linetype="dashed")+
  geom_hline(yintercept=0.343, linetype="dashed")+
  ylab("Z-score PUMA")+
  xlab("Time")+
  theme_classic()+
  theme(legend.position="top",
        text=element_text( size=35, color = "black"), 
        axis.text=element_text(colour = "black", size= 25, face="bold"), 
        axis.line = element_line(colour = 'black', size = 1),
        axis.ticks.y = element_line(size = 1),
        axis.ticks.x = element_blank(),
        axis.line.x = element_line(size = 1), 
        strip.background = element_blank())
```

```{r IMPROVEMNET_SCORES}

interv.exp <- interv.exp %>%
  mutate(Improved = b_DS_PUMA_POST > a_DS_PUMA_PRE)  # TRUE if post-test score is higher

interv.exp %>%
  dplyr::group_by(Training) %>%
  dplyr::summarise(
    Improved_N = sum(Improved, na.rm = TRUE),
    Total_N = n(),  # Explicitly calling dplyr::n() to avoid issues
    Improvement_Percentage = (Improved_N / Total_N) * 100,
    .groups = "drop"  # Avoids unnecessary grouping
  )
```

```{r ANALYSES_BY_TERCILES}

interv.exp%>%
  dplyr::group_by(a_TERC_PUMA_PRE, Training) %>%
  dplyr::summarize(n=length(d_ZS_PUMA_StdGain),
                   M=mean(d_ZS_PUMA_StdGain),
                   SD=sd(d_ZS_PUMA_StdGain))

```

```{r ANCOVA_BY_TERCILES}


# Run ANCOVA separately for each tercile
ancova_results <- interv.exp %>%
  group_by(a_TERC_PUMA_PRE) %>%
  group_modify(~ {
    model <- aov(b_ZS_PUMA_POST ~ Training + a_ZS_PUMA_PRE, data = .x)
    
    # Type III ANOVA
    anova_results <- Anova(model, type = "III")
    
    # Effect Size (Partial Eta Squared)
    eta_sq <- eta_squared(model, partial = TRUE)
    
    # Extract relevant values
    tibble(
      F_Training = anova_results$`F value`[2], 
      df_Training = paste0(anova_results$Df[2], ", ", anova_results$Df[4]),  # Df for Training and residuals
      p_Training = anova_results$`Pr(>F)`[2],
      eta2_Training = eta_sq$Eta2[2],  # Partial eta² for Training
      
      F_Covariate = anova_results$`F value`[3], 
      df_Covariate = paste0(anova_results$Df[3], ", ", anova_results$Df[4]),  # Df for covariate and residuals
      p_Covariate = anova_results$`Pr(>F)`[3],
      eta2_Covariate = eta_sq$Eta2[3]  # Partial eta² for covariate (a_ZS_PUMA_PRE)
    )
  })

# View results
print(ancova_results)
```

```{r T_TESTS_BY_TERCILES}

interv.exp.beg <- subset(interv.exp, a_TERC_PUMA_PRE== "Beginner")
interv.exp.int <- subset(interv.exp, a_TERC_PUMA_PRE== "Intermediate")
interv.exp.pro <- subset(interv.exp, a_TERC_PUMA_PRE== "Proficient")

leveneTest(d_ZS_PUMA_StdGain ~ Training, data = interv.exp.beg)
t.test(d_ZS_PUMA_StdGain ~ Training, data = interv.exp.beg, paired=F, var.equal=T)
cohen.d(d_ZS_PUMA_StdGain ~ Training, data = interv.exp.beg)


leveneTest(d_ZS_PUMA_StdGain ~ Training, data = interv.int)
t.test(d_ZS_PUMA_StdGain ~ Training, data = interv.int, paired=F, var.equal=T)
cohen.d(d_ZS_PUMA_StdGain ~ Training, data = interv.int)

leveneTest(d_ZS_PUMA_StdGain ~ Training, data = interv.pro)
t.test(d_ZS_PUMA_StdGain ~ Training, data = interv.pro, paired=F, var.equal=T)
cohen.d(d_ZS_PUMA_StdGain ~ Training, data = interv.pro)
```

```{r SANKEY}
summary_interv.exp <- interv.exp %>%
  dplyr::group_by(a_TERC_PUMA_PRE, Training, b_TERC_PUMA_POST) %>%
  dplyr::summarize(n = sum(!is.na(ID)), .groups = "drop") %>%
  dplyr::mutate(Percentage = (n / sum(n)) * 100)

summary_interv.exp <- summary_interv.exp %>%
  mutate(
    a_TERC_PUMA_PRE = factor(a_TERC_PUMA_PRE, levels = c("Proficient", "Intermediate", "Beginner")),
    b_TERC_PUMA_POST = factor(b_TERC_PUMA_POST, levels = c("Proficient", "Intermediate", "Beginner"))
  )

summary_interv.exp <- interv.exp %>%
  dplyr::group_by(a_TERC_PUMA_PRE, Training, b_TERC_PUMA_POST) %>%
  dplyr::summarize(n = sum(!is.na(ID)), .groups = "drop") %>%
  dplyr::mutate(
    Percentage = (n / sum(n)) * 100,  # Overall percentage
    Profile_Condition_Percentage = (n / sum(n, na.rm = TRUE)) * 100  # Within each a_TERC_PUMA_PRE & Training group
  ) %>%
  dplyr::group_by(a_TERC_PUMA_PRE, Training) %>% 
  dplyr::mutate(Profile_Condition_Percentage = (n / sum(n, na.rm = TRUE)) * 100) %>%
  dplyr::ungroup()


ggplot(data = summary_interv.exp, aes(axis1 = a_TERC_PUMA_PRE, axis2 = b_TERC_PUMA_POST, y = Percentage)) +
  facet_grid(. ~ Training)+
  geom_alluvium(aes(fill = Training), width = 0.3) +
  geom_stratum(fill = "white", color = "black") +
  geom_text(stat = "stratum", aes(label = after_stat(stratum))) +
  scale_fill_manual(values = c("Individual" = "green", "Peer Interaction" = "purple")) + 
  theme_classic() +
  theme(
    legend.position = "right",
    axis.line = element_blank(),
    axis.ticks = element_blank(),
    axis.text = element_blank()
  )
```

```{r TWO_WAY_ANOVA_TERCILE_PROFILE}
aov_sg_profile <- aov(d_ZS_PUMA_StdGain ~ Training * a_TERC_PUMA_PRE, data = interv.exp)
summary(aov_sg_profile)
eta_squared(aov_sg_profile)

```

```{r DESCROPTIVE_POST_PRE_STD_GAIN_DIVIDED_BY_TERCILES_AND_CONDITION}
interv.exp.long2 <- interv.exp %>%
  pivot_longer(c( "a_ZS_PUMA_PRE",
                  "b_ZS_PUMA_POST",
                  "d_ZS_PUMA_StdGain"
  ), names_to = "Measure")


interv.exp.long2 %>%
  dplyr::group_by(a_TERC_PUMA_PRE, Measure,Training) %>%
  dplyr::summarize(n = length(value),
                   M = mean(value),
                   SD = sd(value))
```

```{r PAIRED_T-TEST_POST_VS_PRE_DIVIDED_BY_TERCILES_AND_CONDITION}

results_t_test <- interv.exp %>%
  dplyr::group_by(a_TERC_PUMA_PRE, Training) %>%  # Group by terciles
  dplyr::summarise(
    t_test = list(t.test(a_ZS_PUMA_PRE, b_ZS_PUMA_POST, paired = TRUE)),  # Run paired t-test
    d = cohen.d(a_ZS_PUMA_PRE, b_ZS_PUMA_POST, paired = TRUE)$estimate   # Compute Cohen's d
  ) %>%
  mutate(
    t_value = map_dbl(t_test, ~ .x$statistic),
    df = map_dbl(t_test, ~ .x$parameter),
    p_value = map_dbl(t_test, ~ .x$p.value)
  ) %>%
  select(a_TERC_PUMA_PRE, Training, t_value, df, p_value, d)  # Keep only relevant columns

print(results_t_test)
```
